version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8088:8080
    environment:
      - POSTGRES_PORT=5433
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=ejerciciogo
  nginx:
    image: nginx:stable-perl
    ports:
      - 88:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

  db:
    image: postgres:13.11-bullseye
    ports:
      - 54332:5433
    env_file:
      - .env
    volumes:
    - ./queries.sql:/docker-entrypoint-initdb.d/queries.sql
